language: scala

matrix:
  include:
  - scala: 2.10.6
    jdk: openjdk7
  - scala: 2.10.6
    jdk: openjdk8
  - scala: 2.11.8
    jdk: openjdk7
  - scala: 2.11.8
    jdk: openjdk8
  - scala: 2.12.8
    jdk: openjdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
